# Deep Learning Basic Autograd

In [3]:
import torch

#### Scalar
> 상수항

In [4]:
scalar1 = torch.tensor([1.])
print(scalar1)

tensor([1.])


In [5]:
scalar2 = torch.tensor([3.])    
print(scalar2)

tensor([3.])


In [6]:
add_scalar = scalar1 + scalar2
print(add_scalar)

tensor([4.])


In [7]:
sub_scalar = scalar1 - scalar2
print(sub_scalar)

tensor([-2.])


In [8]:
mul_scalar = scalar1 * scalar2
print(mul_scalar)

tensor([3.])


In [9]:
div_scalar = scalar1 / scalar2
print(div_scalar)

tensor([0.3333])


In [10]:
torch.add(scalar1, scalar2)

tensor([4.])

In [11]:
torch.sub(scalar1, scalar2)

tensor([-2.])

In [12]:
torch.mul(scalar1, scalar2)

tensor([3.])

In [13]:
torch.div(scalar1, scalar2)

tensor([0.3333])

#### Vector
> 1차원

In [14]:
vector1 = torch.tensor([1., 2., 3.])
print(vector1)

tensor([1., 2., 3.])


In [15]:
vector2 = torch.tensor([4., 5., 6.])
print(vector2)

tensor([4., 5., 6.])


In [16]:
add_vector = vector1 + vector2
print(add_vector)

tensor([5., 7., 9.])


In [17]:
sub_vector = vector1 - vector2
print(sub_vector)

tensor([-3., -3., -3.])


In [18]:
mul_vector = vector1 * vector2
print(mul_vector)

tensor([ 4., 10., 18.])


In [19]:
div_vector = vector1 / vector2
print(div_vector)

tensor([0.2500, 0.4000, 0.5000])


In [20]:
torch.add(vector1, vector2)

tensor([5., 7., 9.])

In [21]:
torch.sub(vector1, vector2)

tensor([-3., -3., -3.])

In [22]:
torch.mul(vector1, vector2)

tensor([ 4., 10., 18.])

In [23]:
torch.div(vector1, vector2)

tensor([0.2500, 0.4000, 0.5000])

In [24]:
# 내적
torch.dot(vector1, vector2)

tensor(32.)

#### Matrix
> 2차원

In [26]:
matrix1 = torch.tensor([[1., 2.], [3., 4.]])
print(matrix1)

tensor([[1., 2.],
        [3., 4.]])


In [27]:
matrix2 = torch.tensor([[5., 6.], [7., 8.]])
print(matrix2)

tensor([[5., 6.],
        [7., 8.]])


In [28]:
sum_matrix = matrix1 + matrix2
print(sum_matrix)

tensor([[ 6.,  8.],
        [10., 12.]])


In [29]:
sub_matrix = matrix1 - matrix2
print(sub_matrix)

tensor([[-4., -4.],
        [-4., -4.]])


In [30]:
mul_matrix = matrix1 * matrix2
print(mul_matrix)

tensor([[ 5., 12.],
        [21., 32.]])


In [31]:
div_matrix = matrix1 / matrix2
print(div_matrix)

tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])


In [32]:
torch.add(matrix1, matrix2)

tensor([[ 6.,  8.],
        [10., 12.]])

In [33]:
torch.sub(matrix1, matrix2)

tensor([[-4., -4.],
        [-4., -4.]])

In [34]:
torch.mul(matrix1, matrix2)

tensor([[ 5., 12.],
        [21., 32.]])

In [35]:
torch.div(matrix1, matrix2)

tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])

In [36]:
matmul_matrix = matrix1 @ matrix2
print(matmul_matrix)

tensor([[19., 22.],
        [43., 50.]])


In [37]:
torch.matmul(matrix1, matrix2)

tensor([[19., 22.],
        [43., 50.]])

#### Tensor
> 3차원 이상

In [38]:
tensor1 = torch.tensor([[[1., 2.], [3., 4.]], [[5., 6.], [7., 8.]]])
print(tensor1)

tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])


In [39]:
tensor2 = torch.tensor([[[9., 10.], [11., 12.]], [[13., 14.], [15., 16.]]])
print(tensor2)

tensor([[[ 9., 10.],
         [11., 12.]],

        [[13., 14.],
         [15., 16.]]])


In [40]:
sum_tensor = tensor1 + tensor2
print(sum_tensor)

tensor([[[10., 12.],
         [14., 16.]],

        [[18., 20.],
         [22., 24.]]])


In [41]:
sub_tensor = tensor1 - tensor2
print(sub_tensor)

tensor([[[-8., -8.],
         [-8., -8.]],

        [[-8., -8.],
         [-8., -8.]]])


In [42]:
mul_tensor = tensor1 * tensor2
print(mul_tensor)

tensor([[[  9.,  20.],
         [ 33.,  48.]],

        [[ 65.,  84.],
         [105., 128.]]])


In [43]:
div_tensor = tensor1 / tensor2
print(div_tensor)

tensor([[[0.1111, 0.2000],
         [0.2727, 0.3333]],

        [[0.3846, 0.4286],
         [0.4667, 0.5000]]])


In [44]:
torch.matmul(tensor1, tensor2)

tensor([[[ 31.,  34.],
         [ 71.,  78.]],

        [[155., 166.],
         [211., 226.]]])

In [45]:
torch.add(tensor1, tensor2)

tensor([[[10., 12.],
         [14., 16.]],

        [[18., 20.],
         [22., 24.]]])

In [46]:
torch.sub(tensor1, tensor2)

tensor([[[-8., -8.],
         [-8., -8.]],

        [[-8., -8.],
         [-8., -8.]]])

In [47]:
torch.mul(tensor1, tensor2)

tensor([[[  9.,  20.],
         [ 33.,  48.]],

        [[ 65.,  84.],
         [105., 128.]]])

In [48]:
torch.div(tensor1, tensor2)

tensor([[[0.1111, 0.2000],
         [0.2727, 0.3333]],

        [[0.3846, 0.4286],
         [0.4667, 0.5000]]])

#### 역전파 코드 예시

In [49]:
if torch.cuda.is_available():
    DEVICE = torch.device('cuda') 
else:
    DEVICE = torch.device('cpu') 

In [50]:
BATCH_SIZE = 64 # 파라미터를 업데이트할 때 계산되는 데이터 수
INPUT_SIZE = 1000 # Input 레이어의 노드 수
HIDDEN_SIZE = 100 # Hidden 레이어의 노드 수
OUTPUT_SIZE = 10 # Output 레이어의 노드 수

In [51]:
# (BATCH_SIZE, INPUT_SIZE)의 크기를 갖는 Input 데이터를 생성하기 위해 torch.randn 함수 활용(표준정규분포를 따르는 Element들로 Tensor가 구성되도록 하는 함수)
# 데이터 Type은 실수(torch.float)
# Gradient 계산이 필요 없는 부분이기 때문에 requires_grad = False (Gradient 계산은 Parameter update 할 때 필요) 
x = torch.randn(BATCH_SIZE, 
                INPUT_SIZE, 
                device = DEVICE, 
                dtype = torch.float, 
                requires_grad = False)  

# (BATCH_SIZE, OUTPUT_SIZE)의 크기를 갖는 정답 데이터도 같은 방식으로 임의로 생성
y = torch.randn(BATCH_SIZE, 
                OUTPUT_SIZE, 
                device = DEVICE,
                dtype = torch.float, 
                requires_grad = False)  

# (INPUT_SIZE, HIDDEN_SIZE)의 크기를 갖는 가중치 행렬 생성
# x와 w1의 행렬 곱을 통해 Hidden 레이어의 노드 수 만큼 연산값이 만들어지게 Update를 해야하는 대상이기 때문에 requires_grad = True 로 설정
w1 = torch.randn(INPUT_SIZE, 
                 HIDDEN_SIZE, 
                 device = DEVICE, 
                 dtype = torch.float,
                 requires_grad = True)

# (HIDDEN_SIZE, OUTPUT_SIZE)의 크기를 갖는 가중치 행렬 생성
# x와 w1의 행렬 곱을 통해 만들어진 Hidden 레이어의 연산 값들과 w2를 행렬 곱하여 Output 레이어의 노드 수 만큼 Output 생성 Update를 해야하는 대상이기 때문에 requires_grad = True 로 설정
w2 = torch.randn(HIDDEN_SIZE,
                 OUTPUT_SIZE, 
                 device = DEVICE,
                 dtype = torch.float,
                 requires_grad = True)  

# 학습 정도를 결정하는 learning_rate 설정
learning_rate = 1e-6                                           
for t in range(1, 501): # 500번 반복
    y_pred = x.mm(w1).clamp(min = 0).mm(w2) # x.mm(w1) : x와 w1의 행렬곱을 의미, clamp : min 값보다 작으면 min값으로 (ReLU와 같음)

    loss = (y_pred - y).pow(2).sum() # pow(2) : 제곱, sum() : 행렬(Tensor)의 모든 element를 더함
    if t % 100 == 0:
        print("Iteration: ", t, "\t", "Loss: ", loss.item()) # loss.item(): tensor type을 Python number type으로 바꿔줌
    loss.backward() # Parameter Update에 사용되는 Gradient 계산                                          

    with torch.no_grad(): # 아래 코드들은 Gradient를 추가 계산하지 않고 고정시킨 상태에서 실행됨                                     
        w1 -= learning_rate * w1.grad # w1 Update
        w2 -= learning_rate * w2.grad # w2 Update              

        w1.grad.zero_() # w1에 저장되어 있는 Gradient를 0으로 초기화             
        w2.grad.zero_() # w2에 저장되어 있는 Gradient를 0으로 초기화

Iteration:  100 	 Loss:  498.07415771484375
Iteration:  200 	 Loss:  2.794325113296509
Iteration:  300 	 Loss:  0.022782614454627037
Iteration:  400 	 Loss:  0.00041088793659582734
Iteration:  500 	 Loss:  5.560443241847679e-05
